### PR TITLE
Update FTG-Frontend

### PR DESCRIPTION
**Pull request by chovyy**
This update of the FTG frontend contains the following changes:

* Added wrapper routines for all metainfo getters and setters
* Added support for zero-sized arrays
* Added `ftg_allocate_and_read` routines which take unallocated pointers and allocatable variables, allocate them according to the stored bounds and read the data afterwards.

I have started to generate `m_ser_ftg.f90`, because I was tired to copy, paste and modify every routine 30 times. That's why the indentation may have changed a bit.

### CODE REVIEW

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
PGI on daint doesn't like it
```
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 2901)
PGF90-S-0188-Argument number 2 (non-allocatable) to ftg_allocate_allocatable_logical_0d: type mismatch (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 2901)
  0 inform,   0 warnings,   2 severes, 0 fatal for ftg_allocate_and_read_pointer_logical_0d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 2914)
PGF90-S-0188-Argument number 2 (non-allocatable) to ftg_allocate_allocatable_logical_1d: type mismatch (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 2914)
  0 inform,   0 warnings,   2 severes, 0 fatal for ftg_allocate_and_read_pointer_logical_1d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 2927)
PGF90-S-0188-Argument number 2 (non-allocatable) to ftg_allocate_allocatable_logical_2d: type mismatch (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 2927)
  0 inform,   0 warnings,   2 severes, 0 fatal for ftg_allocate_and_read_pointer_logical_2d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 2940)
PGF90-S-0188-Argument number 2 (non-allocatable) to ftg_allocate_allocatable_logical_3d: type mismatch (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 2940)
  0 inform,   0 warnings,   2 severes, 0 fatal for ftg_allocate_and_read_pointer_logical_3d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 2953)
PGF90-S-0188-Argument number 2 (non-allocatable) to ftg_allocate_allocatable_logical_4d: type mismatch (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 2953)
  0 inform,   0 warnings,   2 severes, 0 fatal for ftg_allocate_and_read_pointer_logical_4d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 2966)
PGF90-S-0188-Argument number 2 (non-allocatable) to ftg_allocate_allocatable_bool_0d: type mismatch (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 2966)
  0 inform,   0 warnings,   2 severes, 0 fatal for ftg_allocate_and_read_pointer_bool_0d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 2979)
PGF90-S-0188-Argument number 2 (non-allocatable) to ftg_allocate_allocatable_bool_1d: type mismatch (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 2979)
  0 inform,   0 warnings,   2 severes, 0 fatal for ftg_allocate_and_read_pointer_bool_1d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 2992)
PGF90-S-0188-Argument number 2 (non-allocatable) to ftg_allocate_allocatable_bool_2d: type mismatch (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 2992)
  0 inform,   0 warnings,   2 severes, 0 fatal for ftg_allocate_and_read_pointer_bool_2d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3005)
PGF90-S-0188-Argument number 2 (non-allocatable) to ftg_allocate_allocatable_bool_3d: type mismatch (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3005)
  0 inform,   0 warnings,   2 severes, 0 fatal for ftg_allocate_and_read_pointer_bool_3d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3018)
PGF90-S-0188-Argument number 2 (non-allocatable) to ftg_allocate_allocatable_bool_4d: type mismatch (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3018)
  0 inform,   0 warnings,   2 severes, 0 fatal for ftg_allocate_and_read_pointer_bool_4d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3031)
PGF90-S-0188-Argument number 2 (non-allocatable) to ftg_allocate_allocatable_int_0d: type mismatch (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3031)
  0 inform,   0 warnings,   2 severes, 0 fatal for ftg_allocate_and_read_pointer_int_0d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3044)
PGF90-S-0188-Argument number 2 (non-allocatable) to ftg_allocate_allocatable_int_1d: type mismatch (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3044)
  0 inform,   0 warnings,   2 severes, 0 fatal for ftg_allocate_and_read_pointer_int_1d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3057)
PGF90-S-0188-Argument number 2 (non-allocatable) to ftg_allocate_allocatable_int_2d: type mismatch (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3057)
  0 inform,   0 warnings,   2 severes, 0 fatal for ftg_allocate_and_read_pointer_int_2d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3070)
PGF90-S-0188-Argument number 2 (non-allocatable) to ftg_allocate_allocatable_int_3d: type mismatch (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3070)
  0 inform,   0 warnings,   2 severes, 0 fatal for ftg_allocate_and_read_pointer_int_3d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3083)
PGF90-S-0188-Argument number 2 (non-allocatable) to ftg_allocate_allocatable_int_4d: type mismatch (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3083)
  0 inform,   0 warnings,   2 severes, 0 fatal for ftg_allocate_and_read_pointer_int_4d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3096)
PGF90-S-0188-Argument number 2 (non-allocatable) to ftg_allocate_allocatable_long_0d: type mismatch (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3096)
  0 inform,   0 warnings,   2 severes, 0 fatal for ftg_allocate_and_read_pointer_long_0d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3109)
PGF90-S-0188-Argument number 2 (non-allocatable) to ftg_allocate_allocatable_long_1d: type mismatch (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3109)
  0 inform,   0 warnings,   2 severes, 0 fatal for ftg_allocate_and_read_pointer_long_1d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3122)
PGF90-S-0188-Argument number 2 (non-allocatable) to ftg_allocate_allocatable_long_2d: type mismatch (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3122)
  0 inform,   0 warnings,   2 severes, 0 fatal for ftg_allocate_and_read_pointer_long_2d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3135)
PGF90-S-0188-Argument number 2 (non-allocatable) to ftg_allocate_allocatable_long_3d: type mismatch (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3135)
  0 inform,   0 warnings,   2 severes, 0 fatal for ftg_allocate_and_read_pointer_long_3d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3148)
PGF90-S-0188-Argument number 2 (non-allocatable) to ftg_allocate_allocatable_long_4d: type mismatch (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3148)
  0 inform,   0 warnings,   2 severes, 0 fatal for ftg_allocate_and_read_pointer_long_4d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3161)
PGF90-S-0188-Argument number 2 (non-allocatable) to ftg_allocate_allocatable_float_0d: type mismatch (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3161)
  0 inform,   0 warnings,   2 severes, 0 fatal for ftg_allocate_and_read_pointer_float_0d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3174)
PGF90-S-0188-Argument number 2 (non-allocatable) to ftg_allocate_allocatable_float_1d: type mismatch (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3174)
  0 inform,   0 warnings,   2 severes, 0 fatal for ftg_allocate_and_read_pointer_float_1d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3187)
PGF90-S-0188-Argument number 2 (non-allocatable) to ftg_allocate_allocatable_float_2d: type mismatch (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3187)
  0 inform,   0 warnings,   2 severes, 0 fatal for ftg_allocate_and_read_pointer_float_2d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3200)
PGF90-S-0188-Argument number 2 (non-allocatable) to ftg_allocate_allocatable_float_3d: type mismatch (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3200)
  0 inform,   0 warnings,   2 severes, 0 fatal for ftg_allocate_and_read_pointer_float_3d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3213)
PGF90-S-0188-Argument number 2 (non-allocatable) to ftg_allocate_allocatable_float_4d: type mismatch (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3213)
  0 inform,   0 warnings,   2 severes, 0 fatal for ftg_allocate_and_read_pointer_float_4d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3226)
PGF90-S-0188-Argument number 2 (non-allocatable) to ftg_allocate_allocatable_double_0d: type mismatch (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3226)
  0 inform,   0 warnings,   2 severes, 0 fatal for ftg_allocate_and_read_pointer_double_0d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3239)
PGF90-S-0188-Argument number 2 (non-allocatable) to ftg_allocate_allocatable_double_1d: type mismatch (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3239)
  0 inform,   0 warnings,   2 severes, 0 fatal for ftg_allocate_and_read_pointer_double_1d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3252)
PGF90-S-0188-Argument number 2 (non-allocatable) to ftg_allocate_allocatable_double_2d: type mismatch (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3252)
  0 inform,   0 warnings,   2 severes, 0 fatal for ftg_allocate_and_read_pointer_double_2d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3265)
PGF90-S-0188-Argument number 2 (non-allocatable) to ftg_allocate_allocatable_double_3d: type mismatch (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3265)
  0 inform,   0 warnings,   2 severes, 0 fatal for ftg_allocate_and_read_pointer_double_3d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3278)
PGF90-S-0188-Argument number 2 (non-allocatable) to ftg_allocate_allocatable_double_4d: type mismatch (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3278)
  0 inform,   0 warnings,   2 severes, 0 fatal for ftg_allocate_and_read_pointer_double_4d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3294)
  0 inform,   0 warnings,   1 severes, 0 fatal for ftg_allocate_and_read_allocatable_logical_0d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3307)
  0 inform,   0 warnings,   1 severes, 0 fatal for ftg_allocate_and_read_allocatable_logical_1d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3320)
  0 inform,   0 warnings,   1 severes, 0 fatal for ftg_allocate_and_read_allocatable_logical_2d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3333)
  0 inform,   0 warnings,   1 severes, 0 fatal for ftg_allocate_and_read_allocatable_logical_3d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3346)
  0 inform,   0 warnings,   1 severes, 0 fatal for ftg_allocate_and_read_allocatable_logical_4d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3359)
  0 inform,   0 warnings,   1 severes, 0 fatal for ftg_allocate_and_read_allocatable_bool_0d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3372)
  0 inform,   0 warnings,   1 severes, 0 fatal for ftg_allocate_and_read_allocatable_bool_1d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3385)
  0 inform,   0 warnings,   1 severes, 0 fatal for ftg_allocate_and_read_allocatable_bool_2d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3398)
  0 inform,   0 warnings,   1 severes, 0 fatal for ftg_allocate_and_read_allocatable_bool_3d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3411)
  0 inform,   0 warnings,   1 severes, 0 fatal for ftg_allocate_and_read_allocatable_bool_4d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3424)
  0 inform,   0 warnings,   1 severes, 0 fatal for ftg_allocate_and_read_allocatable_int_0d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3437)
  0 inform,   0 warnings,   1 severes, 0 fatal for ftg_allocate_and_read_allocatable_int_1d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3450)
  0 inform,   0 warnings,   1 severes, 0 fatal for ftg_allocate_and_read_allocatable_int_2d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3463)
  0 inform,   0 warnings,   1 severes, 0 fatal for ftg_allocate_and_read_allocatable_int_3d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3476)
  0 inform,   0 warnings,   1 severes, 0 fatal for ftg_allocate_and_read_allocatable_int_4d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3489)
  0 inform,   0 warnings,   1 severes, 0 fatal for ftg_allocate_and_read_allocatable_long_0d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3502)
  0 inform,   0 warnings,   1 severes, 0 fatal for ftg_allocate_and_read_allocatable_long_1d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3515)
  0 inform,   0 warnings,   1 severes, 0 fatal for ftg_allocate_and_read_allocatable_long_2d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3528)
  0 inform,   0 warnings,   1 severes, 0 fatal for ftg_allocate_and_read_allocatable_long_3d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3541)
  0 inform,   0 warnings,   1 severes, 0 fatal for ftg_allocate_and_read_allocatable_long_4d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3554)
  0 inform,   0 warnings,   1 severes, 0 fatal for ftg_allocate_and_read_allocatable_float_0d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3567)
  0 inform,   0 warnings,   1 severes, 0 fatal for ftg_allocate_and_read_allocatable_float_1d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3580)
  0 inform,   0 warnings,   1 severes, 0 fatal for ftg_allocate_and_read_allocatable_float_2d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3593)
  0 inform,   0 warnings,   1 severes, 0 fatal for ftg_allocate_and_read_allocatable_float_3d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3606)
  0 inform,   0 warnings,   1 severes, 0 fatal for ftg_allocate_and_read_allocatable_float_4d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3619)
  0 inform,   0 warnings,   1 severes, 0 fatal for ftg_allocate_and_read_allocatable_double_0d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3632)
  0 inform,   0 warnings,   1 severes, 0 fatal for ftg_allocate_and_read_allocatable_double_1d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3645)
  0 inform,   0 warnings,   1 severes, 0 fatal for ftg_allocate_and_read_allocatable_double_2d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3658)
  0 inform,   0 warnings,   1 severes, 0 fatal for ftg_allocate_and_read_allocatable_double_3d
PGF90-S-0155-Ambiguous interfaces for generic procedure ftg_allocate (/scratch/snx3000/jenkins/workspace/serialbox2_PR/compiler/pgi/slave/daint/src/serialbox-fortran/m_ser_ftg.f90: 3671)
  0 inform,   0 warnings,   1 severes, 0 fatal for ftg_allocate_and_read_allocatable_double_4d
src/serialbox-fortran/CMakeFiles/SerialboxFortranLibraryObjects.dir/build.make:134: recipe for target 'src/serialbox-fortran/CMakeFiles/SerialboxFortranLibraryObjects.dir/m_ser_ftg.f90.o' failed
```

**Comment by chovyy** [comment]
I have now installed PGI, but I have no idea how to configure it. The [documentation](https://eth-cscs.github.io/serialbox2/Building.html#dependencies) just says: "The Cray and PGI compilers are currently not able to compile the C++/C part of Serialbox."
Any hints? How is Jenkins doing it?

**Comment by chovyy** [comment]
Ok, I found out myself that I have to set `CMAKE_Fortran_COMPILER`. Now I'm stuck at compiling pFUnit, but I'm working on it.

**Comment by chovyy** [comment]
That was easy, thanks to your `build.sh`. Now I was able to reproduce the errors.

**Comment by chovyy** [comment]
I guess, I fixed it, though I'm not very happy with the solution. Still wasn't able to run the tests with PGI:

```
[ 94%] Linking CXX executable SerialboxFortranUnittest
/usr/lib/../lib64/crt1.o: In function `_start':
/home/abuild/rpmbuild/BUILD/glibc-2.22/csu/../sysdeps/x86_64/start.S:114: undefined reference to `main'
/usr/bin/ld: link errors found, deleting executable `SerialboxFortranUnittest'
/usr/bin/X11/sha1sum: SerialboxFortranUnittest: Datei oder Verzeichnis nicht gefunden
collect2: error: ld returned 1 exit status
test/serialbox-fortran/CMakeFiles/SerialboxFortranUnittest.dir/build.make:159: recipe for target 'test/serialbox-fortran/SerialboxFortranUnittest' failed
make[2]: *** [test/serialbox-fortran/SerialboxFortranUnittest] Error 1
CMakeFiles/Makefile2:963: recipe for target 'test/serialbox-fortran/CMakeFiles/SerialboxFortranUnittest.dir/all' failed
make[1]: *** [test/serialbox-fortran/CMakeFiles/SerialboxFortranUnittest.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by vectorflux** [comment]
As you might have gathered, Christian's changes are important to us for avoiding the problems with these damned zero-sized arrays...  Thanks for addressing this.

One comment which probably does not fit here:  compare.py always flags differences between NaNs.  Since our arrays frequently contain halo regions which are not defined, it would be more convenient if NaN was considered equal to NaN.  Is this a reasonable thing, or does that open a can of worms in other places?

**Comment by havogt** [comment]
launch jenkins

**Comment by chovyy** [comment]
> 

One comment which probably does not fit here: compare.py always flags differences between NaNs. Since our arrays frequently contain halo regions which are not defined, it would be more convenient if NaN was considered equal to NaN. Is this a reasonable thing, or does that open a can of worms in other places?

I have create [an issue for that](https://github.com/eth-cscs/serialbox2/issues/148).

**Comment by vectorflux** [comment]
Thanks, Christian.  I'm glad it is not a silly (or dangerous) thing to ask for...

**Comment by chovyy** [comment]
Thanks for merging.

There is now a [new release of FTG](https://github.com/fortesg/fortrantestgenerator/releases/tag/v1.4.0) with templates adapted to these changes.

**Comment by chovyy** [comment]
@vectorflux: Please note, that the only way to handle those zero-size arrays was to flag them within the metadata. For that it was necessary to introduce a metadata field that is now required for every field read by the FTG frontend. Unfortunately, that means that you have to recapture all existing data if you want to read it with the new version.

**Pull request merged**
