### PR TITLE
Python visualization

### PR DESCRIPTION
**Pull request by thfabian**
## Technical Description

Port the Visualizer from serialbox1 to serialbox2 and update the documentation accordingly.

**Note**: After this merge the documentation should be deployed again to github (see https://eth-cscs.github.io/serialbox2/Documentation.html) to reflect this update.

### CODE REVIEW

**Comment by thfabian** [comment]
I would stronlgy advice against exporting it in `__init__.py` as forces a dependency on matplotlib on entire serialbox module. I don't think this is worth it for such a niche functionality, no?

**Comment by pspoerri** [comment]
The place where you especially want to use the python integration is for debugging and visualization. We have matplotlib on kesch and daint so it's not a problem.

**Comment by thfabian** [comment]
Yeah but you can still import it, no? And it is clearly stated in the documentation how to do it.. I don't see a problem here but I guess it Hannes call (I don't care :))

**Comment by havogt** [comment]
I tested it following the documentation. Looks good!

**Comment by pspoerri** [comment]
@thfabian I'll let @havogt decide whether he wants to have it in the module or not.

**Comment by havogt** [comment]
It is about an explicit `from serialbox.visualizer import Visualizer`?

**Comment by thfabian** [comment]
Yes it is still part of the module of course but it is not automatically exported as this would force a dependency on matplotlib (even if you don't need it). Instead of writing
```
from serialbox.visualizer import Visualizer
```
you can simply write
```
from serialbox import Visualizer
```
which I think is a small benefit for a hefty price.

**Comment by havogt** [comment]
Yes, I don't care. I am fine with the current state.

**Pull request merged**
