### PR TITLE
 Extend Fortran unit test to expose error in rank calculation 

### PR DESCRIPTION
**Pull request by chovyy**
This is an extension of the unit test for the Fortran interface that exposes the faulty rank calculation which is supposed to be fixed by #17.

The Fortran unit test now crashes with the message: 
```
ERROR: field 'testfield_i0' has rank 1 but field with rank 0 was passed
```

### CODE REVIEW

**Comment by chovyy** [comment]
Sorry for the messy commit history due to some merge and rebase trouble.

**Comment by havogt** [comment]
Cool, thank! Then that is a nice chance to try if jenkins testing works with pfunit. I will try to set it up.

**Comment by chovyy** [comment]
Unfortunately, the test doesn't fail formally but just crashes due to the faulty rank check within Serialbox.

**Comment by havogt** [comment]
No worries, it is still a good test for the jenkins setup. I will have it by tomorrow, then we can merge your PRs.

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
@jenkins-apn yes

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
test this please

**Comment by havogt** [comment]
@jenkins-apn test this please

**Comment by havogt** [comment]
test this please

**Comment by clementval** [comment]
@havogt You have to be nicer with Jenkins :-)

**Comment by havogt** [comment]
it is the official command ;)

**Comment by havogt** [comment]
but still doesn't work.

**Comment by havogt** [comment]
@jenkins-apn ok to test

**Comment by havogt** [comment]
launch jenkins

**Comment by havogt** [comment]
@jenkins-apn test this please

**Comment by havogt** [comment]
finally...

**Comment by havogt** [comment]
I merged this PR already together with #17. Thanks again @chovyy!

**Pull request closed without merging**
