### PR TITLE
Added tolerance file to compare.py

### PR DESCRIPTION
**Pull request by phmarti**
This adds an option to read in a JSON file to provide per field tolerance values.

### CODE REVIEW

**Comment by clementval** [comment]
Makes sense

**Comment by havogt** [comment]
Should we add an example json file?

**Comment by clementval** [comment]
Maybe in the wiki?

**Comment by phmarti** [comment]
There is no wiki for the moment

**Comment by phmarti** [comment]
Example tolerance file:

[tolerance_file.txt](https://github.com/eth-cscs/serialbox2/files/2075616/tolerance_file.txt)

**Comment by clementval** [comment]
It's not `.json` :-D

**Comment by phmarti** [comment]
GitHub doesn't accept .json files :cry:

**Comment by clementval** [comment]
@phmarti fair enough

**Pull request merged**
